site_name: Search Engine Clinical Protocols
theme:
  name: material
nav:
  - Home: index.md
  - Different steps : 
    - Embedding: ./rag/embeddings.md
    - Vector DB: ./rag/vector_db.md
    - Query: ./rag/search.md
  - About: about.md
plugins:
  - search