site_name: RCT RAG
theme:
  name: material
nav:
  - Home: index.md
  - Different steps : 
    - Builder: ./rag/builder.md
    - Sparse Search Engine: ./rag/sparse_engine.md
  - About: about.md
plugins:
  - search