name: Search Engine App

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-root

        
    - name: Download NLTK data
      run: |
        python -m nltk.downloader -d /usr/share/nltk_data punkt wordnet stopwords averaged_perceptron_tagger omw-1.4

    - name: Run tests
      run: |
        pip install pytest
        pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 search_engine builder tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
